-- File generated by Dolibarr 21.0.0 --;

-- Page ID 1__+MAX_llx_website_page__ - Aliases accueil --;
INSERT INTO llx_website_page(rowid, fk_page, fk_website, pageurl, aliasalt, title, description, lang, image, keywords, status, date_creation, tms, import_key, grabbed_from, type_container, htmlheader, content, author_alias, allowed_in_frames) VALUES(1__+MAX_llx_website_page__, null, __WEBSITE_ID__, 'accueil', '', 'accueil', '', '', '', '', '1', '2025-04-01 12:50:09', '2025-04-01 15:57:17', null, '', 'page', '', '<!DOCTYPE html>__N__<html lang=\"en\">__N____N__<body>__N__    <h1>Bonjour</h1>__N__</body>__N__</html>', '', 0);
UPDATE llx_website SET fk_default_home = 1__+MAX_llx_website_page__ WHERE rowid = __WEBSITE_ID__;


-- For Dolibarr v14+ --;
UPDATE llx_website SET lang = 'fr' WHERE rowid = __WEBSITE_ID__;
UPDATE llx_website SET otherlang = '' WHERE rowid = __WEBSITE_ID__;

